# Generated by Django 4.2.6 on 2023-10-08 19:08

from django.conf import settings
from django.db import migrations, models
import main.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Filomenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('Nome', models.CharField(max_length=500, verbose_name='Nome')),
                ('Cpf', models.CharField(max_length=500, verbose_name='Cpf')),
                ('Endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('Telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('Idade', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Idade')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(main.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(main.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Filomena',
                'verbose_name_plural': 'Filomenas',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_filomena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(main.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(main.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Filomenas',
        ),
    ]
